# Seeed Studio XIAO ESP32 S3 Sense
# Spec: https://wiki.seeedstudio.com/xiao_esp32s3_getting_started/
# - 2.4GHz Wi-Fi
# - BLE 5.0
# - OV2640 Camera Sensor
# - Digital Microphone
# - 8MB PSRAM
# - 8MB Flash
# - Battery Charge Supported
# - Rich Interface
# - IoT
# - Embedded ML

substitutions:
  device_name: Camera Demo

esphome:
  name: camera-demo
  # platform: ESP32
  # board: nodemcu-32s

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3

# wifi:
#   ssid: !secret wifi_ssid
#   password: !secret wifi_password
#   domain: !secret domain

# Enable logging
logger:

# Enable Home Assistant API and OTA updates
# api:
#   encryption:
#     key: !secret api_key

# ota:
#   - platform: esphome
#     password: !secret ota_password

# binary_sensor:
#   # A light sensor beams across the pedestrian gate, and also wired to the STOP_CMD switch. The
#   # switch registers 3.3v when the gate is opened.
#   - platform: gpio
#     name: "Pedestrian Gate"
#     device_class: door
#     pin: 12
#   # The driveway gate motor has an open limit and close limit switch connected to the board. The
#   # Close limit switch means the driveway gate is closed, and the open limit switch means that
#   # the gate is all the way open.
#   - platform: gpio
#     name: "Driveway Gate"
#     device_class: door
#     pin:
#         number: 4 
#   - platform: gpio
#     name: "Driveway Gate Full Open"
#     device_class: door
#     pin:
#         number: 5
#         inverted: true


esp32_camera:
  name: My Cam
  external_clock:
    pin: GPIO10  # XMCLK
    frequency: 20MHz
  i2c_pins:
    sda: GPIO40  # CAM_SDA
    scl: GPIO39	 # CAM_SCL
  data_pins:
    - GPIO12  # DVP_Y7
    - GPIO14  # DVP_Y6
    - GPIO16  # DVP_Y5
    - GPIO18  # DVP_Y4
    - GPIO11  # DVP_Y8
    - GPIO15  # DVP_Y2
    - GPIO17  # DVP_Y3
    - GPIO48  # DVP_Y9
  vsync_pin: GPIO38  # DVP_VSYNC
  href_pin: GPIO47  # DVP_HREF
  pixel_clock_pin: GPIO13  # DVP_PCLK
  # Quality settings
  max_framerate: 15 fps   
  idle_framerate: 0.05 fps 
  resolution: 1600x1200
  jpeg_quality: 35



switch:
  - platform: gpio
    name: "My Cam flash"
    pin: 4
