# Seeed Studio XIAO ESP32 S3 Sense
# Spec: https://wiki.seeedstudio.com/xiao_esp32s3_getting_started/
# - 2.4GHz Wi-Fi
# - BLE 5.0
# - OV2640 Camera Sensor
# - Digital Microphone
# - 8MB PSRAM
# - 8MB Flash
# - Battery Charge Supported
# - Rich Interface
# - IoT
# - Embedded ML

substitutions:
  device_name: Camera Demo

esphome:
  name: camera-demo
  platformio_options:
    build_flags: -DBOARD_HAS_PSRAM
    board_build.arduino.memory_type: qio_opi
    board_build.f_flash: 80000000L
    board_build.flash_mode: qio

# esp32:
#   board: esp32-s3-devkitc-1
#   framework:
#     type: arduino

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret domain
  # Power save to reduce heat
  # power_save_mode: high
  output_power: 8.5
  # fast_connect: On

# Enable logging
logger:

# Enable Home Assistant API and OTA updates
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

# Increase frequency to 800kHz https://community.home-assistant.io/t/esphome-wifi-auth-expired/443790/23?page=2
# i2c:
#   sda: GPIO3
#   scl: GPIO1
#   frequency: 800kHz

esp32_camera:
  name: My Cam
  external_clock:
    pin: GPIO10  # XMCLK
    frequency: 10MHz  # Lower from 20MHz to increase reliability  https://www.reddit.com/r/homeassistant/comments/wrqpe4/esphome_esp32_cam_reliability/
  i2c_pins:
    sda: GPIO40  # CAM_SDA
    scl: GPIO39	 # CAM_SCL
  data_pins: 
    - GPIO15  # DVP_Y2
    - GPIO17  # DVP_Y3
    - GPIO18  # DVP_Y4
    - GPIO16  # DVP_Y5
    - GPIO14  # DVP_Y6
    - GPIO12  # DVP_Y7
    - GPIO11  # DVP_Y8
    - GPIO48  # DVP_Y9
  vsync_pin: GPIO38  # DVP_VSYNC
  href_pin: GPIO47  # DVP_HREF
  pixel_clock_pin: GPIO13  # DVP_PCLK
  # Quality settings
  max_framerate: 10 fps   
  idle_framerate: 0.1 fps 
  resolution: VGA
  jpeg_quality: 35
  # Image is far too dark by default
  brightness: 2
