name: ESPHome config 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: 3.12


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: "pip"
        cache-dependency-path: "**/requirements.txt"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure secrets
      run: |
        cp config/secrets-example.yaml sensors/secrets.yaml
        cp config/secrets-example.yaml displays/secrets.yaml
        cp config/secrets-example.yaml camera/secrets.yaml

    - name: Verify configuration files
      run: |
        declare -a config_file
        for config_file in $(find . -maxdepth 2 -type f \( -name "*.yaml" ! -name "secrets*.yaml" \) ); do
            echo Verifying ${config_file}
            esphome config ${config_file}
            esphome compile ${config_file}
        done
