name: ESPHome config 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Configure secrets
      run: |
        cp config/secrets-example.yaml sensors/secrets.yaml
        cp config/secrets-example.yaml playground/secrets.yaml
    - name: Verify configuration files
      run: |
        declare -a config_file
        cp config/secrets-example.yaml config/secrets.yaml
        for config_file in $(find . -maxdepth 2 -type f \( -name "*.yaml" ! -name "secrets*.yaml" \) ); do
            echo Verifying ${config_file}
            esphome ${config_file} config        
        done
